name: Linux x86

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y gcc-multilib libssl-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu
      - run: cargo build --release --target i686-unknown-linux-gnu
      - run: |
          mkdir -p artifact
          cp target/i686-unknown-linux-gnu/release/rustkpcli artifact/
      - uses: actions/upload-artifact@v4
        with:
          name: rustkpcli-linux-x86
          path: artifact/
